"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useRef, useState } from "react";
import { ArrowLeft, Building2, CalendarDays, CheckCircle2, ExternalLink, Mail, Pencil, Phone, Trash2, UserRound, X } from "lucide-react";
import { deleteCompany as removeCompany, updateCompany as saveCompany } from "@/lib/supabase/business-client";
import type { Company, Project } from "@/lib/types";
import { priorityLabels, projectStatusLabels, statusLabels } from "@/lib/i18n";
import { formatDate, isOverdue } from "@/lib/utils";
import { useWorkspace } from "./app-provider";
import { PriorityBadge, StatusBadge } from "./badges";
import { UserAvatar } from "./user-avatar";
import { CompanyFormDialog } from "./company-form-dialog";
import { TaskRow } from "./task-row";
import { ResourceLinksSection } from "./resource-links-section";
import { normalizeWebsiteUrl } from "@/lib/resource-links";

export function CompanyDetailView({ company: initialCompany, projects, linkedTaskCount, loadError = "" }: { company: Company | null; projects: Project[]; linkedTaskCount: number; loadError?: string }) {
  const router = useRouter();
  const { tasks, setSelectedTask } = useWorkspace();
  const [company, setCompany] = useState(initialCompany);
  const [editOpen, setEditOpen] = useState(false);
  const [deleteOpen, setDeleteOpen] = useState(false);
  const [deleteError, setDeleteError] = useState("");
  const [deleteBusy, setDeleteBusy] = useState(false);
  const deleteLock = useRef(false);
  if (loadError) return <div className="panel p-10 text-center text-rose-700">{loadError}</div>;
  if (!company) return <div className="panel p-10 text-center"><h1 className="text-xl font-semibold">Firma bulunamadı</h1><Link href="/companies" className="text-link mt-3 justify-center">Firmalara dön</Link></div>;

  const companyProjects = projects.filter((project) => project.companyId === company.id);
  const projectName = (projectId: string) => projects.find((project) => project.id === projectId)?.name ?? "Proje bulunamadı";
  const activeProjects = companyProjects.filter((project) => project.status !== "On hold");
  const activeTasks = tasks.filter((task) => task.companyId === company.id && task.status !== "Done" && !task.cancelledAt).sort((a, b) => a.dueDate.localeCompare(b.dueDate));
  const completedTasks = tasks.filter((task) => task.companyId === company.id && task.status === "Done" && !task.cancelledAt);
  const companyWebsiteUrl = normalizeWebsiteUrl(company.website);

  return <>
    <Link href="/companies" className="mb-5 inline-flex items-center gap-2 text-xs font-semibold text-slate-500 hover:text-slate-900"><ArrowLeft size={14} />Firmalara dön</Link>
    <header className="panel overflow-hidden"><div className="h-1.5" style={{ backgroundColor: company.color }} /><div className="p-5 sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div className="flex min-w-0 items-start gap-3 sm:gap-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl text-white sm:h-12 sm:w-12" style={{ backgroundColor: company.color }}><Building2 size={22} /></span><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[0.15em] text-slate-400">Firma</p><h1 className="mt-1 break-words text-2xl font-semibold tracking-tight text-slate-950 sm:text-3xl">{company.name}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{company.notes || "Bu firma için henüz not eklenmedi."}</p></div></div><div className="grid grid-cols-2 gap-2 sm:flex sm:shrink-0"><button onClick={() => setEditOpen(true)} className="secondary-button"><Pencil size={14} />Düzenle</button><button onClick={() => setDeleteOpen(true)} className="secondary-button text-rose-600 hover:border-rose-200 hover:bg-rose-50 hover:text-rose-700"><Trash2 size={14} />Firma Sil</button></div></div></div></header>

    <div className="mt-6 grid gap-6 xl:grid-cols-[320px_minmax(0,1fr)]">
      <aside className="space-y-6">
        <ResourceLinksSection ownerType="company" ownerId={company.id} />
        <section className="panel p-5"><h2 className="section-title">Firma Bilgileri</h2><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Yetkili kişi</dt><dd className="mt-1 flex items-center gap-2 font-semibold text-slate-700"><UserRound size={15} className="text-slate-400" />{company.contactName || "Eklenmedi"}</dd></div><div><dt className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Telefon</dt><dd className="mt-1">{company.phone ? <a className="flex items-center gap-2 font-semibold text-slate-700 hover:text-indigo-600" href={`tel:${company.phone.replace(/\s/g, "")}`}><Phone size={15} className="text-slate-400" />{company.phone}</a> : <span className="text-slate-400">Eklenmedi</span>}</dd></div><div><dt className="text-[10px] font-bold uppercase tracking-wide text-slate-400">E-posta</dt><dd className="mt-1">{company.email ? <a className="flex items-center gap-2 break-all font-semibold text-slate-700 hover:text-indigo-600" href={`mailto:${company.email}`}><Mail size={15} className="text-slate-400" />{company.email}</a> : <span className="text-slate-400">Eklenmedi</span>}</dd></div><div><dt className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Web sitesi</dt><dd className="mt-1">{companyWebsiteUrl ? <a className="flex items-center gap-2 break-all font-semibold text-indigo-600 hover:text-indigo-800" href={companyWebsiteUrl} target="_blank" rel="noopener noreferrer"><ExternalLink size={14} />{company.website}</a> : company.website ? <span className="break-all text-rose-600">Geçersiz web sitesi adresi</span> : <span className="text-slate-400">Eklenmedi</span>}</dd></div><div><dt className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Notlar</dt><dd className="mt-1 leading-6 text-slate-500">{company.notes || "Not eklenmedi."}</dd></div></dl></section>
        <section className="panel overflow-hidden"><div className="panel-header"><div><h2 className="section-title">Aktif Projeler</h2><p className="section-subtitle">{activeProjects.length} proje sürüyor</p></div></div><div className="divide-y divide-slate-100">{activeProjects.length ? activeProjects.map((project) => <Link key={project.id} href={`/projects/${project.id}`} className="block p-4 hover:bg-slate-50"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold text-slate-800">{project.name}</p><p className="mt-1 text-[11px] text-slate-400">{project.progress}% tamamlandı</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-600">{projectStatusLabels[project.status]}</span></div></Link>) : <p className="p-5 text-sm text-slate-400">Bu firmaya bağlı aktif proje yok.</p>}</div></section>
      </aside>

      <div className="space-y-6">
        <section className="panel overflow-hidden"><div className="panel-header"><div><h2 className="section-title">Görevler / Yapılacaklar</h2><p className="section-subtitle">{activeTasks.length} aktif görev</p></div></div><div className="sm:hidden">{activeTasks.length ? activeTasks.map((task) => <TaskRow key={task.id} task={task} compact />) : <p className="p-5 text-sm text-slate-400">Bu firmaya bağlı aktif görev yok.</p>}</div><div className="hidden overflow-x-auto sm:block"><div className="min-w-[760px]"><div className="grid grid-cols-[minmax(210px,1.5fr)_110px_52px_92px_110px] gap-3 border-b border-slate-100 bg-slate-50/70 px-4 py-2 text-[10px] font-bold uppercase tracking-wide text-slate-400"><span>Görev / Proje</span><span>Durum</span><span>Sorumlu</span><span>Öncelik</span><span>Son Tarih</span></div>{activeTasks.map((task) => <button key={task.id} onClick={() => setSelectedTask(task)} className="grid w-full grid-cols-[minmax(210px,1.5fr)_110px_52px_92px_110px] items-center gap-3 border-b border-slate-100 px-4 py-3 text-left last:border-0 hover:bg-slate-50"><span className="min-w-0"><span className="block truncate text-sm font-semibold text-slate-800">{task.title}</span><span className="mt-0.5 block truncate text-[11px] text-slate-400">{projectName(task.projectId)}</span></span><StatusBadge status={task.status} /><UserAvatar userId={task.assigneeId} size="sm" /><span title={priorityLabels[task.priority]}><PriorityBadge priority={task.priority} /></span><span className={`text-xs font-semibold ${isOverdue(task) ? "text-rose-600" : "text-slate-600"}`}><span className="flex items-center gap-1"><CalendarDays size={13} />{formatDate(task.dueDate)}</span>{isOverdue(task) ? <span className="mt-0.5 block text-[10px] font-bold">Gecikti</span> : null}</span></button>)}</div></div></section>
        <section className="panel overflow-hidden"><div className="panel-header"><div className="flex items-center gap-2"><CheckCircle2 size={17} className="text-emerald-600" /><h2 className="section-title">Tamamlanan İşler</h2></div><span className="text-xs font-semibold text-slate-400">{completedTasks.length} görev</span></div><div className="divide-y divide-slate-100">{completedTasks.length ? completedTasks.map((task) => <button key={task.id} onClick={() => setSelectedTask(task)} className="flex w-full items-center gap-3 px-5 py-3 text-left hover:bg-slate-50"><CheckCircle2 size={16} className="shrink-0 text-emerald-500" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-500 line-through">{task.title}</p><p className="mt-0.5 text-[11px] text-slate-400">{projectName(task.projectId)} · {statusLabels[task.status]}</p></div><UserAvatar userId={task.assigneeId} size="sm" /></button>) : <p className="p-6 text-sm text-slate-400">Henüz tamamlanan iş yok.</p>}</div></section>
      </div>
    </div>
    {editOpen ? <CompanyFormDialog company={company} onCancel={() => setEditOpen(false)} onSave={async (input) => { try { setCompany(await saveCompany(company.id, input)); setEditOpen(false); } catch { throw new Error("Firma güncellenemedi."); } }} /> : null}
    {deleteOpen ? <div className="responsive-dialog z-[70]" role="dialog" aria-modal="true" aria-labelledby="delete-company-title">
      <button type="button" className="absolute inset-0" onClick={() => { if (!deleteBusy) setDeleteOpen(false); }} aria-label="Silme penceresini kapat" />
      <section className="responsive-dialog-panel max-w-md"><header className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h2 id="delete-company-title" className="text-sm font-semibold text-slate-950">Firmayı Sil</h2><button disabled={deleteBusy} onClick={() => setDeleteOpen(false)} className="icon-button" aria-label="Kapat"><X size={18} /></button></header><div className="responsive-dialog-body p-5"><p className="text-sm font-semibold text-slate-800">{company.name} silinsin mi?</p>{companyProjects.length || linkedTaskCount ? <div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-sm font-semibold text-amber-900">Bu firma şu anda silinemez.</p><p className="mt-1 text-xs leading-5 text-amber-700">Firmaya bağlı {companyProjects.length} proje ve {linkedTaskCount} görev var. Önce bu ilişkileri kaldırmanız gerekir.</p></div> : <p className="mt-2 text-xs leading-5 text-slate-500">Firma kaydı kalıcı olarak silinecektir.</p>}{deleteError ? <p className="mt-3 text-xs font-semibold text-rose-600">{deleteError}</p> : null}</div><footer className="responsive-dialog-footer"><button disabled={deleteBusy} onClick={() => setDeleteOpen(false)} className="secondary-button">İptal</button><button disabled={deleteBusy || Boolean(companyProjects.length || linkedTaskCount)} onClick={async () => { if (deleteLock.current) return; deleteLock.current = true; setDeleteBusy(true); try { await removeCompany(company.id); setDeleteOpen(false); router.push("/companies"); router.refresh(); } catch (error) { setDeleteError(error instanceof Error ? error.message : "Firma silinemedi."); deleteLock.current = false; setDeleteBusy(false); } }} className="primary-button bg-rose-600 hover:bg-rose-700 disabled:cursor-not-allowed disabled:bg-slate-300">{deleteBusy ? "Siliniyor…" : "Firma Sil"}</button></footer></section>
    </div> : null}
  </>;
}
